# Generated by Django 5.2.9 on 2026-05-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usersession_logout_time_alter_usersession_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='imagen',
            field=models.ImageField(default='C:\\Users\\ESTUDIANTE\\Desktop\\proyecto_sena\\project\\static\\img\\user.jpg', upload_to='imagenes/'),
        ),
    ]
