# Generated by Django 4.2 on 2026-05-20 00:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/post/imagenes/'),
        ),
        migrations.AddField(
            model_name='postimagen',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalog.post'),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='catalog.post'),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='catalog/post/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov'])]),
        ),
    ]
